#!/bin/sh

sudo apt-get install python3
sudo apt-get -y install python3-pip

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo copy $DIR/smartlock to /etc/ini.d folder

sudo cp $DIR/smartlock /etc/init.d

cd ..

echo Install Python requirements...

pip3 install -r requirements.txt

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

sudo chmod a+x $DIR/run.py

sudo chmod 755 /etc/init.d/smartlock

sudo systemctl enable smartlock

sudo systemctl daemon-reload
